name: live
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  infinity_page_view: ^1.0.0
  flutter_swiper: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true


  assets:
#       - images/

#        - images/access_module/
#        - images/base_module/

        #access_module
        - images/access_module/access_guide_bg.png
        - images/access_module/access_login_bg.png

        #base_module
        - images/base_module/ic_textfiled_delete.png
        - images/base_module/ic_vip.png
        - images/base_module/ic_drawer_bg.png

        - images/base_module/drawer_close.png
        - images/base_module/drawer_coupon.png
        - images/base_module/drawer_friend.png
        - images/base_module/drawer_location.png
        - images/base_module/drawer_night.png
        - images/base_module/drawer_playgame.png
        - images/base_module/drawer_setting.png
        - images/base_module/drawer_vip.png



